apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "twin-reflector-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "twin-reflector-proxy.name" . }}
    helm.sh/chart: {{ include "twin-reflector-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "twin-reflector-proxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "twin-reflector-proxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: COM_MICROSOFT_TWINS_TWINSURL
              valueFrom:
                secretKeyRef:
                  name: twins
                  key: twins-url
            - name: COM_MICROSOFT_TWINS_AAD_TENANT
              valueFrom:
                secretKeyRef:
                  name: twins
                  key: aad-tenant
            - name: COM_MICROSOFT_TWINS_AAD_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: twins
                  key: aad-client-id
            - name: COM_MICROSOFT_TWINS_AAD_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: twins
                  key: aad-client-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
