apiVersion: v1
kind: Secret
metadata:
  name: twins
type: Opaque
data:
  twins-url: {{ .Values.adt.url | b64enc | quote}}
  aad-tenant: {{ .Values.adt.aad.tenant  | b64enc | quote}}
  aad-client-id: {{ .Values.adt.aad.clientId  | b64enc | quote}}
  aad-client-secret: {{ .Values.adt.aad.clientSecret  | b64enc | quote}}
  event-hubs-connection-string: {{ .Values.eventHubs.connectionString  | b64enc | quote}}
  event-hubs-secondary-connection-string: {{ .Values.eventHubs.secondaryConnectionString  | b64enc | quote}}
  event-hubs-namespace: {{ .Values.eventHubs.namespace  | b64enc | quote}}