# Default values for twin-reflector-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: twin-reflector-proxy
  tag: latest
  pullPolicy: IfNotPresent

adt:
  url:
  aad:
    tenant:
    clientId:
    clientSecret:
eventHubs:
  connectionString:
  secondaryConnectionString:
  namespace:

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ssl-redirect: "true"
  hosts:
    - proxy.westeurope.cloudapp.azure.com
  paths:
    - /
  tls:
    enabled: true
    email: you.mail@comes.here
    secretName: tls-secret-proxy

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
